[theme]
base = "light"
primaryColor = "#6C63FF"         # Soft violet for buttons and highlights
backgroundColor = "#F9F9F9"      # Light grey background
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"            # Dark gray text
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[client]
toolbarMode = "minimal"
